version: '3'
services:
  schema_service:
    image: registry.gitlab.com/datainsider/schema-service:oss
    container_name: rocket-schema-service
    restart: always
    environment:
      NAME: schema-service
      MODE: production
      HTTP_PORT: 8489
      THRIFT_PORT: 8487
      CLICKHOUSE_HOST: ""
      CLICKHOUSE_HTTP_PORT: 8123
      CLICKHOUSE_TCP_PORT: 9000
      CLICKHOUSE_USERNAME: default
      CLICKHOUSE_PASSWORD: ""
      CLICKHOUSE_CLUSTER_NAME: ""
    ports:
      - "8489:8489"
      - "8487:8487"
    volumes:
      - ./conf:/app/conf
      - ./logs:/app/logs
networks:
  default:
    external:
      name: rocket_network
